### ISSUE TITLE
Main header animation on the index page interferes with the animations on the navigation bar. 

### ISSUE THREAD

**Issue by StevenGreve** [StevenGreve/my-website#3]
# Problem 
If you hover over the navigation bar on the landing page, you will experience problems when you try to navigate to another section. That's because the whole line – on which the header is placed – is sensitive to any kind of hovering. As a result of this, the user would have to wait for the right moment, before he clicks on one of the navigation links. Otherwise, both the animation of the main header and the animations of the navigation links will pause, and thus, the user will be unable to change the page. 

---

# Solution
One possible (but temporary) solution would be opt for a hamburger menu on the landing page, regardless of the screen size. However, since this isn't entirely user friendly either, I will instead try to deactivate the header animation whenever the user hovers over the navigation bar.

**Comment by hentai-chan** [comment]
Easy fix: remove your title animation.

**Comment by StevenGreve** [comment]
lmao
